config/routes.rb
Rails.application.routes.draw do
  resources :gamers
  resources :gaming_sessions, only: %i[index new create destroy]
  resources :platforms do
    resources :video_games
  end
  resources :sessions, only: %i[create destroy]
  get "/", to: "sessions#index"
  get "/signin", to: "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gamer.rb
class Gamer < ApplicationRecord
  has_many :gaming_sessions
  has_many :video_games, through: :gaming_sessions
  has_many :platforms, through: :video_games
  has_secure_password

  validates :name, :gamertag, :password, presence: true
  validates_uniqueness_of :gamertag

  PASSWORD_REQUIREMENTS = /\A
    (?=.{8}) # At least 8 characters long
    (?=.*\d) # Contrains at least one number
    (?=.*[a-z]) # Contains at least one lowercase letter
    (?=.*[A-Z]) # Contains at least one uppercase letter
    (?=.*[[:^alnum:]]) # Contains at least one symbol
  /x.freeze

  validates :password, format: PASSWORD_REQUIREMENTS
end

app/models/gaming_session.rb
class GamingSession < ApplicationRecord
  belongs_to :gamer
  belongs_to :video_game

  def readable_start_time
    start_time.to_date.strftime("%B %d, %Y")
  end

  def session_length
    length = (end_time - start_time) / 60 / 60
    length.round(1)
  end
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :video_games
  has_many :gamers, through: :video_games

  validates :name, :developer, :release_date, presence: true
  validates_uniqueness_of :name

  def readable_release_date
    release_date.to_date.strftime("%B %d, %Y")
  end
end

app/models/video_game.rb
class VideoGame < ApplicationRecord
  has_many :gaming_sessions
  has_many :gamers, through: :gaming_sessions
  belongs_to :platform
  validates :name, :release_date, :genre, presence: true
  validates :name, uniqueness: { scope: :platform, case_sensitive: false }
  scope :new_games, -> { where("release_date >= '2020-01-01'") }

  def message
    "This game has already been added to this platform."
  end

  def readable_release_date
    release_date.to_date.strftime("%B %d, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
  before_action :require_login

private

  def require_login
    redirect_to "/signin" unless session.include? :gamer_id
  end
end

app/controllers/gamers_controller.rb
class GamersController < ApplicationController
  before_action :set_gamer, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[new create]

  def index
    @gamers = Gamer.all
  end

  def show
    @gaming_sessions = @gamer.gaming_sessions.sort_by(&:start_time).reverse
    @platforms = @gamer.platforms.uniq
    @video_games = @gamer.video_games.uniq
  end

  def new
    redirect_to "/" if session.include? :gamer_id

    @gamer = Gamer.new
  end

  def create
    @gamer = Gamer.new(gamer_params)

    if @gamer.save
      redirect_to signin_path
    else
      render "new"
    end
  end

  def edit
    redirect_to gamers_path unless session[:gamer_id] == @gamer.id
  end

  def update
    @gamer.update(gamer_params)

    redirect_to gamer_path(@gamer)
  end

  def destroy
    @gamer.gaming_sessions.each(&:delete)
    @gamer.destroy
    session.delete :gamer_id

    redirect_to "/"
  end

private

  def gamer_params
    params.require(:gamer).permit(:name, :gamertag, :password)
  end

  def set_gamer
    @gamer = Gamer.find(params[:id])
  end
end

app/controllers/gaming_sessions_controller.rb
class GamingSessionsController < ApplicationController
  before_action :set_gamer
  skip_before_action :set_gamer, only: :index

  def index
    @gaming_sessions = GamingSession.all.sort_by(&:start_time).reverse
  end

  def new
    @gaming_session = GamingSession.new(start_time: DateTime.now, end_time: DateTime.now)
  end

  def create
    @gaming_session = GamingSession.new(gaming_session_params)

    if @gaming_session.save
      redirect_to gamer_path(@gamer)
    else
      render "new"
    end
  end

  def destroy
    @gaming_session = GamingSession.find(params[:id])
    @gaming_session.delete

    redirect_to gamer_path(@gamer)
  end

private

  def gaming_session_params
    params.require(:gaming_session).permit(:gamer_id, :video_game_id, :start_time, :end_time)
  end

  def set_gamer
    @gamer = Gamer.find(session[:gamer_id])
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: %i[show edit update]

  def index
    @platforms = Platform.all
  end

  def show
    @gamers = @platform.gamers
  end

  def new
    @platform = Platform.new
  end

  def create
    @platform = Platform.new(platform_params)
    if @platform.save
      redirect_to platform_path(@platform)
    else
      render "new"
    end
  end

  def edit
    @release_date = @platform.release_date.to_date
  end

  def update
    @platform.update(platform_params)

    redirect_to platform_path(@platform)
  end

private

  def platform_params
    params.require(:platform).permit(:name, :release_date, :developer)
  end

  def set_platform
    @platform = Platform.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def index
    return unless session[:gamer_id]

    @gamer = Gamer.find(session[:gamer_id])
    @new_games = VideoGame.new_games
  end

  def new
    redirect_to "/" if session.include? :gamer_id
  end

  def create
    @gamer = Gamer.find_by(gamertag: params[:gamertag])

    return redirect_to "/signin" unless @gamer&.authenticate(params[:password])

    session[:gamer_id] = @gamer.id
    redirect_to "/"
  end

  def destroy
    session.delete :gamer_id

    redirect_to signin_path
  end
end

app/controllers/video_games_controller.rb
class VideoGamesController < ApplicationController
  before_action :set_platform
  before_action :set_video_game, only: %i[show edit update destroy]

  def index
    @video_games = VideoGame.where("platform_id = ?", params[:platform_id])
  end

  def show; end

  def new
    @video_game = VideoGame.new
  end

  def create
    @video_game = VideoGame.new(video_game_params)

    if @video_game.save
      redirect_to platform_video_game_path(@platform, @video_game)
    else
      @release_date = @video_game.release_date.to_date
      render "new"
    end
  end

  def edit
    @release_date = @video_game.release_date.to_date
  end

  def update
    @video_game.update(video_game_params)

    redirect_to platform_video_game_path(@platform, @video_game)
  end

  def destroy
    @video_game.delete

    redirect_to platform_video_games_path(@platform)
  end

private

  def video_game_params
    params.require(:video_game).permit(:name, :genre, :platform_id, :release_date)
  end

  def set_platform
    @platform = Platform.find(params[:platform_id])
  end

  def set_video_game
    @video_game = VideoGame.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header
    if session[:gamer_id].blank?
      render "header_logged_out"
    else
      @gamer = Gamer.find(session[:gamer_id])
      render "header_logged_in"
    end
  end
end

app/helpers/gamers_helper.rb
module GamersHelper
  def member_since
    @gamer.created_at.to_date.strftime("%B %d, %Y")
  end

  def delete_if_signed_in
    return unless session[:gamer_id] == @gamer.id

    link_to "delete", gaming_session_path(@session), method: :delete
  end

  def edit_gamer_if_signed_in
    return unless session[:gamer_id] == @gamer.id

    link_to "Edit Profile", edit_gamer_path(@gamer)
  end

  def delete_gamer_if_signed_in
    return unless session[:gamer_id] == @gamer.id

    link_to "Delete Profile", gamer_path(@gamer), method: :delete
  end
end

app/helpers/gaming_sessions_helper.rb
module GamingSessionsHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def welcome
    if session[:gamer_id].blank?
      render "welcome_gamers"
    else
      render "welcome_gamer"
    end
  end
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/application/_header_logged_in.html.erb
<header>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand">Video Game App</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><%= link_to "My Profile", gamer_path(@gamer) %></li>
      </ul>
      <%= button_to "Sign Out", session_path(@gamer), method: "delete", class: "btn btn-danger navbar-btn" %>
    </div>
  </nav>
</header>

app/views/application/_header_logged_out.html.erb
<header>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Video Game App</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/gamers/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/signin"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </nav>
</header>

app/views/application/_welcome_gamer.html.erb
<h1>Welcome <%= @gamer.name %></h1>

<%= link_to "New gaming session", new_gaming_session_path %><br>

<%= link_to "Platforms", platforms_path %><br><br>

<%= link_to "Sign Out", session_path(@gamer), method: :delete %>

app/views/gamers/_form.html.erb
<h1>Create Profile</h1>

<%= form_for @gamer do |f| %>
  <% if @gamer.errors.any? %>
    <% @gamer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %><br>
  <% end %>

  <%= f.label :name, "Name: " %>
  <%= f.text_field :name %><br>

  <%= f.label :gamertag, "Gamertag: " %>
  <%= f.text_field :gamertag %><br>

  <%= f.label :password, "Password: " %>
  <%= f.password_field :password %><br><br>

  <%= f.submit %>
<% end %>

app/views/gamers/index.html.erb
<h1>All Gamers</h1>
<% @gamers.each do |gamer| %>
  <%= link_to gamer.gamertag, gamer_path(gamer) %><br>
<% end %>

app/views/gamers/new.html.erb
<%= form_for @gamer do |f| %>
  <%= f.label :name, "Name: " %>
  <%= f.text_field :name %><br>

  <%= f.label :username, "Username: " %>
  <%= f.text_field :username %><br>

  <%= f.label :password, "Password: " %>
  <%= f.text_field :password %><br>

  <%= f.submit %>
<% end %>

app/views/gamers/show.html.erb
<h1><%= @gamer.gamertag %></h1>
  <em>member since: <%= member_since %></em><br><br>

<h3>Video Games:</h3>
  <ul>
    <% @video_games.each do |video_game| %>
      <li><%= video_game.name %><br></li>
    <% end %>
  </ul>

<h3>Platforms:</h3>
  <ul>
    <% @platforms.each do |platform| %>
      <li><%= platform.name %></li>
    <% end %>
  </ul>

<h3>Recent Gaming Sessions:</h3>
  <% @gaming_sessions.each do |gaming_session| %>
    <% @session = gaming_session %>
    <%= @gamer.gamertag %> played <%= gaming_session.video_game.name %> on <%= gaming_session.readable_start_time %> for <%= gaming_session.session_length %> hour(s) <%= delete_if_signed_in %><br>

  <% end %><br>

  <%= edit_gamer_if_signed_in %>
  <%= delete_gamer_if_signed_in %>

<%# add in gaming stats %>

app/views/gaming_sessions/index.html.erb
<h1>Recent Gaming Sessions</h1>
<% @gaming_sessions.each do |session| %>
     <%= session.gamer.gamertag %> played <%= session.video_game.name %> on <%= session.readable_start_time %> for <%= session.session_length %> hour(s)<br>
  <% end %><br>

app/views/gaming_sessions/new.html.erb
<h1>New Gaming Session</h1>
<%= form_for @gaming_session do |f| %>
  <%= f.hidden_field :gamer_id, value: @gamer.id %>

  <%= f.label :video_game_id, "What game did you play?" %>
  <%= f.collection_select :video_game_id, VideoGame.all, :id, :name %><br>
    <em>or add a new game <%= link_to "here", platforms_path %></p><br></em>

  <%= f.label :start_time %>
  <%= f.datetime_field :start_time %><br>

  <%= f.label :end_time %>
  <%= f.datetime_field :end_time %><br><br>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video Game App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= header %>

  <div class=container>
    <body>
      <%= yield %>
    </body>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

app/views/platforms/_form.html.erb
<h1>New Platform </h1>
<%= form_for @platform do |f| %>
  <% if @platform.errors.any? %>
    <% @platform.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %><br>
  <% end %>

  <%= f.label :name, "Name: " %>
  <%= f.text_field :name %><br>

  <%= f.label :developer, "Develper: "%>
  <%= f.text_field :developer %><br>

  <%= f.label :release_date, "Release Date: "%>
  <%= f.date_field :release_date, value: @release_date %><br><br>

  <%= f.submit %>
<% end %>

app/views/platforms/edit.html.erb
<%= render "form" %>

app/views/platforms/index.html.erb
<h1>Platforms</h1>

<ul>
  <% @platforms.each do |platform| %>
    <li><%= link_to platform.name, platform_path(platform) %></li>
  <% end %>
</ul><br>

<%= link_to "New Platform", new_platform_path %>

app/views/platforms/new.html.erb
<%= render "form" %>

app/views/platforms/show.html.erb
<h1><%= @platform.name %></h1>

<strong>Developer: </strong>
<%= @platform.developer %><br>

<strong>Release Date: </strong>
<%= @platform.readable_release_date %><br><br>

<h3>Gamers: </h3>
  <% @gamers.each do |gamer| %>
    <%= gamer.gamertag %><br>
  <% end %><br>

<%= link_to "Edit this platform", edit_platform_path(@platform) %><br>
<%= link_to "Video Games on this platforn", platform_video_games_path(@platform) %>

app/views/video_games/_form.html.erb
<h1>Add a new game to <%= @platform.name %></h1>
<%= form_for [@platform, @video_game] do |f| %>
  <% if @video_game.errors.any? %>
    <% @video_game.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %><br>
  <% end %>

  <%= f.hidden_field :platform_id, value: @platform.id %>

  <%= f.label :name, "Name: " %>
  <%= f.text_field :name %><br>

  <%= f.label :genre, "Genre: " %>
  <%= f.text_field :genre %><br>

  <%= f.label :release_date, "Release date: " %>
  <%= f.date_field :release_date, start_year: 1980, end_year: 2020, value: @release_date %><br><br>

  <%= f.submit %>
<% end %>

app/views/video_games/index.html.erb
<h1><%= @platform.name %> Games</h1>

<% @video_games.each do |game| %>
  <%= link_to game.name, platform_video_game_path(@platform, game) %><br>
<% end %><br>

<%= link_to "Add a new video game on #{@platform.name}", new_platform_video_game_path %>

app/views/video_games/show.html.erb
<h1><%= @video_game.name %></h1>
  <strong>Platform: </strong>
  <%= @platform.name %><br>

  <strong>Genre: </strong>
  <%= @video_game.genre %><br>

  <strong>Release Date: </strong>
  <%= @video_game.readable_release_date %><br><br>

<%= link_to "Edit", edit_platform_video_game_path(@platform, @video_game) %>
<%= link_to "Delete", platform_video_game_path(@platform, @video_game), method: :delete %>